Задание 1
RomanLuperkal/Test-task pull request #4
Opened 2024-04-17 20:04 UTC by RomanLuperkal

2024-04-21 15:49 UTC, GUR-ok commented
В первую очередь поправить конфликты. Локально подтяни в эту ветку девелоп, устранив конфликты или сделай ребейз

2024-04-21 15:49 UTC, GUR-ok commented
Давай назовем мр "Task1: add price increase scheduling" а не "Задание 1". именно с таким комментарием в итоге смержится сквошнутый коммит в девелоп

2024-04-21 16:07 UTC, GUR-ok requested changes

2024-04-21 16:07 UTC, GUR-ok commented on pom.xml
> +            <artifactId>spring-context</artifactId>
Для чего эта либа тут?

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/aspect/TimeTrackTransactionAspect.java
> +        } finally {
А чем отличается от первого аспекта? Это не замерит время коммита транзакции. Ты проверял на обычном шедулере, что когда время вывелось, ты наблюдаешь измнеенные данные в бд? На большом числе записей проверить.
Обычно делают через 
```
        try {
            return joinPoint.proceed();
        } finally {
            TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization(){
                public void afterCommit(){
                    stopWatch.stop();
                    System.out.println("Execution time for " + className + "." + methodName + " :: " + stopWatch.getTime() + " ms");
                }
            });
        }
  ```

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/configuration/AspectConfiguration.java
> +@EnableAspectJAutoProxy
In Spring Boot projects, we don’t have to explicitly use the @EnableAspectJAutoProxy. There’s a dedicated [AopAutoConfiguration](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/aop/AopAutoConfiguration.html) that enables Spring’s AOP support if the Aspect or Advice is on the classpath.

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/configuration/SchedulingConfiguration.java
> +
Лишние пустые строки

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/configuration/SchedulingConfiguration.java
> +    }
тут не хватает пустой строки

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/configuration/SchedulingConfiguration.java
> +    @Profile("default")
Profile("!local) по заданию. это немного отличается от @Profile("default")

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/SimpleProductPriceScheduler.java
> +            final BigDecimal actualPrice = p.getPrice();
в приватный метод мб

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/SimpleProductPriceScheduler.java
> +    @Value("${app.scheduling.priceIncrease}")
А так заинжектится прям bigdecimal? не ругается?

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/SimpleProductPriceScheduler.java
> +    @Autowired
без autowired

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +import java.sql.*;
избегаем схлопнутых импортов. настрой идею плз, чтоб не схлопывала автоматом

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +                while (true) {
while(true) с брейком это плохо.

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +                    System.out.println("Обновлено " + updatedRows + " строк");
sout не должно быть в боевом закоммиченном коде. через логирование

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +            } catch (SQLException e) {
роллбэк потерялся и давай ловить все Exception e

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +        String updateSQL = "UPDATE product SET price = price + (price / 100) * " + priceIncrease + " WHERE uuid = ?";
не нужно вычисления делать на стороне бд, не нужно лишний раз нагружать cpu бд, вычисления лучше делать в сервисе.

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +        try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM product");
лишний селект в бд - это основная ошибка. мы же уже извлекали resultset для обновления.
Сделай примерно так плз (или в точности так). Отличие от втоего кода в том, что тут все клозится атвоматом, в бд 1 селект, а не 2. Нет ручной пагинации и контроля числа извлеченных записей.
```
    @Scheduled(fixedRateString = "${app.scheduling.period}")
    public void increaseProductPrice() {
        log.info("Start optimized scheduling");
        final Session session = entityManagerFactory.createEntityManager().unwrap(Session.class);

        try (session) {
            session.doWork(new Work() {
                @Override
                public void execute(Connection connection) throws SQLException {
                    try (
                            BufferedWriter fileWriter = new BufferedWriter(new FileWriter("results.txt"));
                            connection
                    ) {
                        connection.setAutoCommit(false);
                        long rowCounter = 0L;

                        if (exclusiveLock) {
                            String lock = "LOCK TABLE products IN ACCESS EXCLUSIVE MODE";
                            Statement lockStatement = connection.createStatement();
                            lockStatement.execute(lock);
                        }

                        String selectQuery = "SELECT * FROM products FOR UPDATE";
                        Statement statement = connection.createStatement();

                        String updateQuery = "UPDATE products SET PRICE = ? WHERE id = ?";
                        PreparedStatement preparedStatement = connection.prepareStatement(updateQuery);

                        ResultSet rs = statement.executeQuery(selectQuery);
                        while (rs.next()) {
                            fileWriter.write(buildString(rs, rowCounter));
                            fileWriter.newLine();

                            preparedStatement.setBigDecimal(1, getNewPrice(rs.getBigDecimal("price"), priceIncreasePercentage));
                            preparedStatement.setObject(2, UUID.fromString(rs.getString("id")));
                            preparedStatement.addBatch();

                            rowCounter++;
                            if (rowCounter % 100000 == 0) {
                                preparedStatement.executeBatch();
                                log.debug("Rows updated: " + rowCounter);
                            }
                        }
                        preparedStatement.executeBatch();

                        log.debug("Committing");
                        connection.commit();
                    } catch (Exception e) {
                        connection.rollback();
                        throw new RuntimeException(e);
                    }
                }
            });
        }
        log.info("End optimized scheduling");
    }
```

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +        log.info("End optimized scheduler");
сессия не клозится

2024-04-21 16:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +        String sql = "SELECT uuid FROM product ORDER BY uuid LIMIT ? OFFSET ?";
ручная пагинация, высчитывание страниц - это все лишнее. можно 1 раз сделать селект и resultset будет содержать курсор на все записи, проходимся по нему по очереди в while(rs.next()) и все. Пример кода будет ниже

2024-04-21 16:24 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/aspect/TimeTrackTransactionAspect.java
> +        } finally {
Этот аспект отличается от первого тем, что у него самый высокий приоритет. Поэтому его логика выполняется первее, чем у аспекта Transactional. Еще раз проверил, данные обновляются только при втором выводе времени с сообщением из этого аспекта

2024-04-21 17:30 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +        try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM product");
Я вижу, что тут в файл записывается не обновленное значение строк а их состояние перед обновлением. Это так и задумано?

2024-04-21 17:37 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +        try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM product");
нужно поправить, спасибо )

2024-04-21 17:40 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +        try (PreparedStatement statement = connection.prepareStatement("SELECT * FROM product");
```
    @Scheduled(fixedRateString = "${app.scheduling.period}")
    public void increaseProductPrice() {
        log.info("Start optimized scheduling");
        final Session session = entityManagerFactory.createEntityManager().unwrap(Session.class);

        try (session) {
            session.doWork(new Work() {
                @Override
                public void execute(Connection connection) throws SQLException {
                    try (
                            BufferedWriter fileWriter = new BufferedWriter(new FileWriter("results.txt"));
                            connection
                    ) {
                        connection.setAutoCommit(false);
                        long rowCounter = 0L;

                        if (exclusiveLock) {
                            String lock = "LOCK TABLE products IN ACCESS EXCLUSIVE MODE";
                            Statement lockStatement = connection.createStatement();
                            lockStatement.execute(lock);
                        }

                        String selectQuery = "SELECT * FROM products FOR UPDATE";
                        Statement statement = connection.createStatement();

                        String updateQuery = "UPDATE products SET PRICE = ? WHERE id = ?";
                        PreparedStatement preparedStatement = connection.prepareStatement(updateQuery);

                        ResultSet rs = statement.executeQuery(selectQuery);
                        while (rs.next()) {
                            final BigDecimal newPrice = getNewPrice(rs.getBigDecimal("price"), priceIncreasePercentage);
                            preparedStatement.setBigDecimal(1, newPrice);
                            preparedStatement.setObject(2, UUID.fromString(rs.getString("id")));
                            preparedStatement.addBatch();

                            fileWriter.write(buildString(rs, rowCounter, newPrice));
                            fileWriter.newLine();
                            
                            rowCounter++;
                            if (rowCounter % 100000 == 0) {
                                preparedStatement.executeBatch();
                                log.debug("Rows updated: " + rowCounter);
                            }
                        }
                        preparedStatement.executeBatch();

                        log.debug("Committing");
                        connection.commit();
                    } catch (Exception e) {
                        connection.rollback();
                        throw new RuntimeException(e);
                    }
                }
            });
        }
        log.info("End optimized scheduling");
    }
```

2024-04-21 18:03 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/aspect/TimeTrackTransactionAspect.java
> +        } finally {
ок, но он работает только совместно с кастомной аннотацией? нам нужно по дефолту мерить все Transactional в приложении без добавления своей

2024-04-21 18:11 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/aspect/TimeTrackTransactionAspect.java
> +        } finally {
Т.е. у нас 3 случая:
1. если висит кастомная аннотация - то измеряем время работы чистого метода
2. кастомная аннотация + transactional - измеряем время работы чистого время и коммита транзакции
3. transactional - измеряем время работы транзакции без измерения отдельно чистого метода
Я правильно все понял ?

2024-04-21 18:16 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/aspect/TimeTrackTransactionAspect.java
> +        } finally {
Если оставить @Around("@annotation(org.springframework.transaction.annotation.Transactional)") наверно тоже должно работать. Проверь плз и подтверди

2024-04-21 18:17 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/aspect/TimeTrackTransactionAspect.java
> +        } finally {
п.2 не нужен

2024-04-21 18:17 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/aspect/TimeTrackTransactionAspect.java
> +        } finally {
п 3 - измеряем время работы от начала тела метода до конца коммита транзакции

2024-04-21 18:22 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/aspect/TimeTrackTransactionAspect.java
> +        } finally {
Да, работает. п.2 при этом тоже соблюдается. Если честно, я думал что измерять какое либо время необходимо только при наличии кастомной аннотации..

2024-04-22 04:13 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/OptimizedProductPriceScheduler.java
> +        String updateSQL = "UPDATE product SET price = price + (price / 100) * " + priceIncrease + " WHERE uuid = ?";
вопрос снят

2024-04-25 11:25 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/sheduling/SimpleProductPriceScheduler.java
> +            final BigDecimal actualPrice = p.getPrice();
Не совсем понял замечание, в приватный метод scheduleFixedDelayTask() обернуть? Так тогда получается @Transactional не выйдет на него вешать

2024-04-25 11:26 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/sheduling/SimpleProductPriceScheduler.java
> +    @Value("${app.scheduling.priceIncrease}")
![image](https://github.com/RomanLuperkal/Test-task/assets/104627970/40af21b8-5967-430e-890a-28b7bde74be3)

2024-04-25 11:28 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/sheduling/SimpleProductPriceScheduler.java
> +    @Autowired
Оно тогда не инжектится и вылетает NPE. или имеется в виду другой тип внедрения использовать ?

2024-04-25 11:33 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/sheduling/SimpleProductPriceScheduler.java
> +    @Value("${app.scheduling.priceIncrease}")
![image](https://github.com/RomanLuperkal/Test-task/assets/104627970/1bf5c03d-0f7d-4198-aa8f-b455556b2f95)

2024-04-25 11:48 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/SimpleProductPriceScheduler.java
> +    @Autowired
requiredargsconstructor добавить и поле сделать final

2024-04-25 11:50 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/sheduling/SimpleProductPriceScheduler.java
> +            final BigDecimal actualPrice = p.getPrice();
приватный метод который принимает ProductEntity, расчитывает новую цену и сеттит ее в энтити. лямбду можно будет заменить на ссылку на метод this:newPrivateMethod(p)

2024-04-25 12:23 UTC, GUR-ok approved these changes

2024-04-25 12:28 UTC, GUR-ok approved these changes

2024-04-25 12:35 UTC, merged