Task2: add search products witch conditions
RomanLuperkal/Test-task pull request #5
Opened 2024-04-24 22:35 UTC by RomanLuperkal

2024-04-27 07:45 UTC, GUR-ok requested changes

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/controller/ProductController.java
> +import com.warehouse.myshop.product.dto.*;
импорты разворачиваем

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/controller/ProductController.java
> +    public ResponseEntity<ListProductDto> searchProducts(@RequestBody @Valid List<FilterConditionDto<?>> conditions,
У GET методов нельзя передавать body в запросе - грубая ошибка

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/enums/Operation.java
> +    LIKE(new String[]{"LIKE", "~"});
LIKE можно взять из названия же самого экземпляра енума.. Еще у енумов можно добавлять поля. сделай так
```
package com.crudshop.demo.service.search.enums;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum OperationType {

    EQUAL("="),
    GRATER_THAN_OR_EQ(">="),
    LESS_THAN_OR_EQ("<="),
    LIKE("~");

    private final String code;

    OperationType(String code) {
        this.code = code;
    }

    @JsonValue
    public String getCode() {
        return code;
    }

    @JsonCreator
    public static OperationType fromCode(String code) {
        for (OperationType operationType : OperationType.values()) {
            if (operationType.name().equals(code) || operationType.code.equals(code)) {
                return operationType;
            }
        } return null;
    }
}
```
или вообще так
```
import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonProperty;

public enum OperationType {
    @JsonProperty("operation")
    @JsonAlias({"="})
    EQUAL,

    @JsonProperty("operation")
    @JsonAlias({">="})
    GRATER_THAN_OR_EQ,

    @JsonProperty("operation")
    @JsonAlias({"<="})
    LESS_THAN_OR_EQ,

    @JsonProperty("operation")
    @JsonAlias({"~"})
    LIKE;
}
```

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/service/ProductServiceImpl.java
> +import com.warehouse.myshop.product.dto.*;
импорты

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/service/ProductService.java
> +import com.warehouse.myshop.product.dto.*;
импорты

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +    public static class NumericFilterConditionDto extends  FilterConditionDto<BigDecimal>{
давай в отдельные файлы плз

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +    public static class NumericFilterConditionDto extends  FilterConditionDto<BigDecimal>{
двойной пробел после extends

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/enums/Operation.java
> +    EQUALS(new String[]{"EQUALS", "="}),
очень странное беспробельное форматирование. как будто код копировал из другого места. поправить форматирование везде. ctrl alt L

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +                case EQUALS:
почему тут нет equals?

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +                case EQUALS:
и тут

2024-04-27 07:45 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +                    return (root, query, cb) -> cb.equal(root.get(this.field), this.value);
из-за того, что создаешь Specification<Product>, у тебя тут везде анонимные классы. мб будем делать не спецификацию, а предикат на этом этапе?

2024-04-27 07:51 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +public abstract class FilterConditionDto<T> {
Почему выбрал абстрактный класс, а не интерфейс? Зачем мы храним спецификацию как проперти, а не имеем метод для ее получения? Если поле value поменяется, спецификация останется старой? Мб поля value field и operation final тогда?

2024-04-27 18:44 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +                case EQUALS:
Насколько я понял из дискуссии в чате можно было EQUALS прировнять к LIKE для даты создания и цены. Если необходимо, могу добавить.

2024-04-27 18:44 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +                case EQUALS:
Насколько я понял из дискуссии в чате можно было EQUALS прировнять к LIKE для даты создания и цены. Если необходимо, могу добавить.

2024-04-27 18:54 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +                    return (root, query, cb) -> cb.equal(root.get(this.field), this.value);
Не совсем понял, чем моя реализация плоха? Если создавать предикат, то по факту я же тоже объект возвращать какой то буду

2024-04-27 18:58 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +public abstract class FilterConditionDto<T> {
Я хотел вынести все поля, т.к. не хотелось их дублировать но про final не подумал. Буду переделывать

2024-05-01 10:41 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +                case EQUALS:
ок

2024-05-01 10:42 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/dto/FilterConditionDto.java
> +                case EQUALS:
ок

2024-05-01 10:42 UTC, GUR-ok approved these changes

2024-05-01 10:42 UTC, GUR-ok commented
можно мержить со сквошем

2024-05-02 13:09 UTC, merged