Task 3: Added currency exchange rate conversion
RomanLuperkal/Test-task pull request #6
Opened 2024-05-01 09:58 UTC by RomanLuperkal

2024-05-01 11:04 UTC, GUR-ok requested changes

2024-05-01 11:04 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/configuration/CachingConfig.java
> +@EnableCaching
enablecaching над главным классом. этот конфиг убрать тк он пустой

2024-05-01 11:04 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/currency/client/CurrencyServiceClientImpl.java
> +    private final WebClient webClient;
Давай конфигурационным классом создадим бин WebClient с хостом от currency-service и заинжектим именно его сюда

2024-05-01 11:04 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/currency/client/CurrencyServiceClientImpl.java
> +    @Value("${currency-service.methods.get-currency}")
Давай больше не будем инжектить через value.
Создай класс для пропертей для rest взаимодействия
@ConfigurationProperties

2024-05-01 11:04 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/currency/client/CurrencyServiceClientImpl.java
> +        this.webClient = WebClient.builder().baseUrl(url).build();
конструктор уберется

2024-05-01 11:04 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/currency/client/CurrencyServiceClientImpl.java
> +    private <T> T performGetRequest(String uri, Class<T> clazz) {
универсальный вебклиент наверно не очень удобен в использовании. каждый раз при вызове из сервиса нужно будет инжектить конфиг-проперти и передавать урл.. еще и класс тут передавать в аргументах.. Давай сделаем конкретный метод без дженерика. урл не принимаем в аргументах, берем из конфигов тут. вызывать будет очень удобно и просто

2024-05-01 11:04 UTC, GUR-ok commented on pom.xml
> +            <groupId>com.github.ben-manes.caffeine</groupId>
это в стартер не входит?

2024-05-01 11:04 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/service/ProductServiceImpl.java
> +                return objectMapper.readValue(readJsonResource("exchange-rate.json"), ResponseCurrencyDto.class);
Не нравится, что ProductService ходит тут в файл за валютой.
Нужно сделать обертку, которая по валюте отдает курс. Она обращается сначала к клиенту, а потом читает из файла. Работа с ресурсом файла будет там и работа с CurrencyServiceClient тоже будет там.
Называем класс ExchangeRateProvider
```
@Component
@Slf4j
@RequiredArgsConstructor
public class ExchangeRateProvider {

    private final CurrencyServiceClient currencyServiceClient ;
```    
Например имеет
1. удобный публичный метод, который позволит передать валюту, а в ответ получит курс. не нужно будет в продукт-сервисе много логики городить. Вызвал и все.
```
public BigDecimal getExchangeRate(Currency currency) {
    return Optional.ofNullable(getExchangeRateFromService(currency))
            .orElseGet(() -> getExchangeRateFromFile(currency));
}
```
2. Сделай два приватных метода. получение валюты из внешнего сервиса и получение из файла
 ```
 private @Nullable BigDecimal getExchangeRateFromService(Currency currency) {
    log.info("Получаем курс из второго сервиса или из кэша");
    return Optional.ofNullable(currencyServiceClient.getExchangeRate())
            .map(rate -> getExchangeRateByCurrency(rate, currency)).orElse(null);
}

private BigDecimal getExchangeRateFromFile(Currency currency) {
...
}

private BigDecimal getExchangeRateByCurrency(ExchangeRate exchangeRate, Currency currency) {
    return switch (currency) {
        case USD -> exchangeRate.getExchangeRateUSD();
        case CNY -> exchangeRate.getExchangeRateCNY();
        case EUR -> exchangeRate.getExchangeRateEUR();
        case RUB -> BigDecimal.ONE;
    };
}
```

2024-05-01 11:04 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/filter/ExceptionHandlerFilter.java
> +    private void handleCurrencyException(HttpServletResponse response, CurrencyException e) throws IOException {
хендлер для исключений у нас же в другом месте

2024-05-01 11:04 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/filter/ExceptionHandlerFilter.java
> +public class ExceptionHandlerFilter extends OncePerRequestFilter {
не оч понимаю зачем вообще этот класс. ну т.е понимаю, что для обработки CurrencyException.. но может его просто не будем бросать, а неправильную валюту игнорить?

2024-05-01 11:04 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/filter/CurrencyFilter.java
> +                if (currency != null) {
Сделай в енуме Currency, чтобы при получении енума из строки при неверной валюте просто null возвращалось. Тут условие задать через 
```
        Optional.ofNullable(currency)
           .map(Currency::valueOf)
           .ifPresent(currencyProvider::setCurrency);
```
Исключение не бросать, лишний фильтр для хендлинга исключений не делать.

2024-05-02 13:50 UTC, RomanLuperkal commented on pom.xml
> +            <groupId>com.github.ben-manes.caffeine</groupId>
Без этих 2х зависимостей ругается, что A component required a bean named 'cacheManager' that could not be found.

2024-05-02 20:48 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/product/service/ProductServiceImpl.java
> +                return objectMapper.readValue(readJsonResource("exchange-rate.json"), ResponseCurrencyDto.class);
Классный вариант! Взял на заметку

2024-05-04 09:53 UTC, GUR-ok requested changes

2024-05-04 09:53 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/currency/client/CurrencyServiceClientImpl.java
> +@ConditionalOnExpression("!${currency-service.mock}")
убрать тут @ConditionalOnExpression а на моке поставить primary

2024-05-04 09:53 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/currency/client/CurrencyServiceClientMock.java
> +@ConditionalOnExpression("${currency-service.mock}")
тут добавить primary и активацию по @ConditionalOnProperty(name = "rest.currency-service.mock.enabled:false")

2024-05-04 09:53 UTC, GUR-ok commented on src/main/resources/application.yml
> +currency-service:
```
rest:
   currency-service:
      host:
      methods: ...
      mock:
         enabled: true
```

2024-05-04 12:27 UTC, GUR-ok approved these changes
мерж со сквошем

2024-05-04 12:28 UTC, merged