Task 4: add Ordering goods
RomanLuperkal/Test-task pull request #8
Opened 2024-05-08 19:30 UTC by RomanLuperkal

![image](https://github.com/RomanLuperkal/Test-task/assets/104627970/61f04a4b-a3f2-48fa-bd39-6197b753fee5)

2024-05-11 12:24 UTC, GUR-ok requested changes

2024-05-11 12:24 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/order/service/OrderServiceImpl.java
> +        List<Product> products = (ArrayList<Product>) productRepository.findAllById(productIds);
кастинг убрать. создать метод в репозитории List<Product> findAllByIdIn(Set<UUID> ids) и его тут вызывать

2024-05-11 12:24 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/cart/model/Cart.java
> +public class Cart {
Cart это корзина. Это большая сущность как заказ. у тебя в одном заказе много cart? Это вводит в заблуждение. Давай например OrderItem, OrderedProduct, OrderProductItem

2024-05-11 12:24 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/order/service/OrderServiceImpl.java
> +            Product product = products.stream().filter(p -> p.getUuid().equals(shortProduct.getId())).findFirst()
квадратичная алгоритмическая сложность. цикл в цикле. сделай хэшмапу из products. ключ это айдишник товара, значение - сам товар. и ходи в эту хэшмапу тут вместо products.stream().filter(p -> p.getUuid()
Так делается примерно хэшмапа
![image](https://github.com/RomanLuperkal/Test-task/assets/76206833/963b0704-ca7e-4ddd-bd09-a99f1f2a0822)

2024-05-11 12:24 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/order/service/OrderServiceImpl.java
> +            Optional<Cart> optionalCart = carts.stream().filter(c -> c.getProduct().getUuid().equals(shortProduct.getId())).findFirst();
аналогичная проблема с циклом в цикле

2024-05-11 12:24 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/order/service/OrderServiceImpl.java
> +        Order order = orderRepository.findOrderWithCustomerByOrderId(orderId)
зачем нам здесь весь ордер? я понимаю, что для проверки кастомер. так может проекции сразу получать тоже, учитывая customerId? Или раз уж дернул заказ, ну выдерни его сджойнив в него сразу его товары

2024-05-11 12:24 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/order/service/OrderServiceImpl.java
> +            if (optionalCart.isPresent()) {
if (optionalCart.isPresent()) else заменить на Optional - map(..) - orElseGet

2024-05-11 12:24 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/cart/repository/CartRepository.java
> +package com.warehouse.myshop.cart.repository;
По пакетам разбито странно. пакет с репозиториями должен быть 1

2024-05-11 12:24 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/order/service/OrderServiceImpl.java
> +        List<ProductDto> products = cartRepository.findOrderProductsByOrderId(orderId);
вот так я делал сразу с кастомером
```
    @Query("""
                select new com.crudshop.demo.entity.projection.ProductProjection (
                    op.orderedProductKey.productId,
                    pe.description,
                    op.quantity,
                    op.price
                  )
                from OrderedProduct op
                  join ProductEntity pe on pe.id = op.orderedProductKey.productId
                  join OrderEntity oe on oe.id = op.orderedProductKey.orderId
                where op.orderedProductKey.orderId = :orderId
                and oe.customer.id = :customerId
            """)
    List<ProductProjection> getProjectionsByOrderIdAndCustomerId
            (UUID orderId, UUID customerId);
```

2024-05-12 13:14 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/order/service/OrderServiceImpl.java
> +        Order order = orderRepository.findOrderWithCustomerByOrderId(orderId)
Здесь заказ получается сразу с пользователем. Делается это для того, что бы понять какое исключение пробросить (отсутствие товара\отсутствие у пользователя прав на товар)

2024-05-12 13:15 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/cart/repository/CartRepository.java
> +package com.warehouse.myshop.cart.repository;
У меня на каждую сущность по 1 репозиторию

2024-05-21 05:04 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/cart/repository/CartRepository.java
> +package com.warehouse.myshop.cart.repository;
я понял да. мне это не понравилось.. потом при мре в мастер ребята посмотрят еще раз на пакеты

2024-05-21 05:12 UTC, GUR-ok approved these changes

2024-05-21 05:12 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/order/service/OrderServiceImpl.java
> +        Order order = orderRepository.findOrderWithCustomerByOrderId(orderId)
Ок. Этот запрос сейчас выглядит как джойн двух таблиц (order и customer). Как вариант можем получить только customerId по orderId, запрос будет чуть легче. По логике если не нашли, то искл-е "заказ не найден", если customerId не совпадает, то ошибка доступа. Можно и так оставить, тк если у нас ORM, то нужно его придерживаться, а не плодить нативные запросы, с другой стороны будет менее нагруженный запрос. Можно оставить короче, на твое усмотрение.

2024-05-21 05:12 UTC, GUR-ok commented
Апрув прожал, на комент ответил

2024-05-21 19:56 UTC, merged