Task 5: Complex business logic has been implemented
RomanLuperkal/Test-task pull request #9
Opened 2024-05-20 21:18 UTC by RomanLuperkal

2024-06-01 10:07 UTC, GUR-ok requested changes

2024-06-01 10:07 UTC, GUR-ok commented on lombok.config
> +lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Qualifier
расскажи плз для чего это

2024-06-01 10:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/account/AccountProvider.java
> +public class AccountProvider {
класс не нужен. он никакой логики не добавляет

2024-06-01 10:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/configuration/WebClientConfiguration.java
> +    @Bean(name = "AccountServiceWebClient")
не нужно внутри аннотации bean писать названия для квалифаера. назови просто сам метод так. с маленькой буквы

2024-06-01 10:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/service/ProductServiceImpl.java
> +            CompletableFuture<Map<UUID, List<OrderInfo>>> featureOrderInfo = featureAccountNumbers
1.  CompletableFuture<Map<UUID, List<OrderInfo>>> featureOrderInfo - неверно. Будет просто Map<UUID, List<OrderInfo>>. А вообще сразу его заретурним 
2. внутри это хардкорного стрима у коллекций, обернутых в completableFuture вызывай join, чтобы дождаться значения внутри.
3. когда работаем с CompletableFuture, то join предпочтительней get, тк не заставляет обрабатывать checked ex
4. Структура итогового стрима
```
        var map = orders.stream()
                .flatMap(ord -> ord.getProds().stream().map(it -> new AbstractMap.SimpleEntry<Prod, Ord>(it, ord)))
                .collect(
                        Collectors.groupingBy(
                                it -> it.getKey().getName(),
                                Collectors.mapping(
                                        it -> it.getValue().getUuid(),
                                        Collectors.toList()
                                )
                        )
                );
```
Вместо Entry можно использовать спринговую Pair

2024-06-01 10:07 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/orderedproduct/repository/OrderedProductRepository.java
> +    Set<OrderedProduct> findFullOrderedProductsWithStatusCreatedOrConfirmed();
Кажется, что это лишний метод, тк получая список order'ов, мы итак получаем всю нужную инфу. Нужно стараться использовать то, что есть. иначе можно расплодить кучу дублирующих друг друга методов. Придется правда переделать стрим (скинул пример там)

2024-06-01 11:12 UTC, GUR-ok commented on src/main/java/com/warehouse/myshop/product/service/ProductServiceImpl.java
> +            CompletableFuture<Map<UUID, List<OrderInfo>>> featureOrderInfo = featureAccountNumbers
Вот еще пример
```
        CompletableFuture<Map<String, String>> accountNumbersByLoginsFuture = accountServiceClient.getAccountNumbersByLogins(logins);

        CompletableFuture<Map<String, String>> innByLoginsFuture = crmServiceClient.getInnByLogins(logins);

        return activeOrders.stream()
                .flatMap(order -> order.getOrderProducts().stream())
                .collect(Collectors.groupingBy(
                        orderProduct -> orderProduct.getProduct().getUuid(),
                        Collectors.mapping(orderProduct -> {
                            Order order = orderProduct.getOrder();
                            Customer customer = order.getCustomer();
                            return new OrderInfo(order.getUuid(),
                                    new CustomerInfo(customer.getId(),
                                            accountNumbersByLoginsFuture.join().get(customer.getLogin()),
                                            customer.getEmail(),
                                            innByLoginsFuture.join().get(customer.getLogin())
                                    ),
                                    order.getStatus(),
                                    order.getDeliveryAddress(),
                                    orderProduct.getQuantity()
                            );
                        }, Collectors.toList())
                ));
    }
```

2024-06-02 11:56 UTC, RomanLuperkal commented on lombok.config
> +lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Qualifier
Это нужно для того, что бы Lombok при обработке аннотации @RequiredArgsConstructor учитывал @Qualifier

2024-06-02 11:59 UTC, RomanLuperkal commented on src/main/java/com/warehouse/myshop/orderedproduct/repository/OrderedProductRepository.java
> +    Set<OrderedProduct> findFullOrderedProductsWithStatusCreatedOrConfirmed();
Нет, это единственный метод для получения списка всех сущностей заказ-товар решающий N + 1. Я нашел у себя метод получающий Set<Order> но он вообще нигде не использовался. Поэтому был удален в последнем комите.

2024-06-08 09:26 UTC, GUR-ok approved these changes
Давай подмержим со сквошем!

2024-07-09 20:55 UTC, merged